global:
  resolve_timeout: 1m
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'SENDER_EMAIL'
  smtp_auth_username: 'SENDER_EMAIL'
  smtp_auth_password: 'SENDER_PASSWORD'
  smtp_require_tls: true

route:
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  receiver: 'email-alert'

receivers:
- name: 'email-alert'
  email_configs:
  - to: 'rj.vlak@student.avans.nl'
    send_resolved: true