services:
  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-eindopdracht}
    volumes:
      - mongo-dev-data:/data/db
    networks:
      - devops-net

  messagebus:
    image: rabbitmq:3-management
    hostname: "messagebus"
    ports:
      - "15673:15672"
      - "5673:5672"
    networks:
      - devops-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 80
      MONGO_URL: ${MONGO_URL:-mongodb://root:secret@mongo:27017/eindopdracht?authSource=admin}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@messagebus:5672}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:80"
    depends_on:
      - mongo
      - messagebus
    networks:
      - devops-net
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - API_URL=${FRONTEND_API_URL:-http://localhost:3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - devops-net
    command: ["npm", "run", "start", "--", "--host", "0.0.0.0", "--poll=2000"]

  db-exporter:
    image: percona/mongodb_exporter:0.40 
    ports:
      - "9216:9216"
    environment:
      MONGODB_URI: ${MONGO_URL:-mongodb://root:secret@mongo:27017/admin?authSource=admin}
    command:
      - "--collect-all"
      - "--compatible-mode"
    networks:
      - devops-net
    depends_on:
      - mongo


  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    env_file:
      - .env
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
    entrypoint:
      - /bin/sh
      - -c
      - |
        # Kopieer naar tmp om de Docker volume beveiliging te omzeilen
        cp /etc/alertmanager/alertmanager.yml /tmp/alertmanager.yml
        sed -i "s|SENDER_EMAIL|$${GMAIL_EMAIL}|g" /tmp/alertmanager.yml
        sed -i "s|SENDER_PASSWORD|$${GMAIL_APP_PASSWORD}|g" /tmp/alertmanager.yml
        /bin/alertmanager --config.file=/tmp/alertmanager.yml
    networks:
      - devops-net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert.rules:/etc/prometheus/alert.rules
    ports:
      - "9090:9090"
    depends_on:
      - api
      - db-exporter
    networks:
      - devops-net
    
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile
    ports:
      - "3001:3000" 
    depends_on:
      - prometheus
    networks:
      - devops-net

networks:
  devops-net:
    driver: bridge
volumes:
  mongo-dev-data: