services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-eindopdracht}
    volumes:
      - ./data/db:/data/db
    networks:
      - devops-net

  messagebus:
    image: rabbitmq:3-management
    container_name: messagebus
    hostname: "messagebus"
    labels:
      NAME: "messagebus"
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    networks:
      - devops-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: 80
      MONGO_URL: ${MONGO_URL:-mongodb://root:secret@mongo:27017/eindopdracht?authSource=admin}
      RABBITMQ_URL: ${RABBITMQ_URL:-amqp://guest:guest@messagebus:5672}
    ports:
      - "80:80"
    depends_on:
      - mongo
      - messagebus
    networks:
      - devops-net
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: eindopdracht-frontend:prod
    environment:
      - API_URL=${FRONTEND_API_URL:-/api}
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - devops-net

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: eindopdracht-frontend:dev
    environment:
      - API_URL=${FRONTEND_API_URL:-http://localhost:3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - devops-net
    command: ["npm","run","start","--","--host","0.0.0.0","--poll=2000"]


networks:
  devops-net:
    driver: bridge