services:
  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secret}
      MONGO_INITDB_DATABASE: ${MONGO_DB:-eindopdracht}
    volumes:
      - ./data/db:/data/db
    networks:
      - devops-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      PORT: ${PORT:-3000}
      MONGO_URL: ${MONGO_URL:-mongodb://root:secret@mongo:27017/eindopdracht?authSource=admin}
    ports:
      - "${HOST_PORT:-3000}:${PORT:-3000}"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    networks:
      - devops-net
    
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    image: eindopdracht-frontend:prod
    environment:
      - API_URL=${FRONTEND_API_URL:-http://localhost:3000}
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - devops-net

  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: eindopdracht-frontend:dev
    environment:
      - API_URL=${FRONTEND_API_URL:-http://localhost:3000}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "4200:4200"
    networks:
      - devops-net
    command: ["npm","run","start","--","--host","0.0.0.0","--poll=2000"]


networks:
  devops-net:
    driver: bridge