name: CI-API

on:
  push:
    branches:
      - main
      - development
    paths:
      - 'week2/**'
  pull_request:
    branches:
      - main
    paths:
      - 'week2/**'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./week2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'week2/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        working-directory: ./
        run: npm run lint
        continue-on-error: true 

      - name: Run Tests & Jest Coverage Report
        if: github.event_name == 'pull_request' || github.ref != 'refs/heads/main'
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          working-directory: week2
          package-manager: npm
          test-script: npm test
          threshold: 80

      - name: Run Tests (Main branch fix)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npm test -- --coverage --ci --watchAll=false
